/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllProjectsAllProjectRouteImport } from './routes/all-projects/AllProject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllProjectsAllProjectRoute = AllProjectsAllProjectRouteImport.update({
  id: '/all-projects/AllProject',
  path: '/all-projects/AllProject',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-projects/AllProject': typeof AllProjectsAllProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-projects/AllProject': typeof AllProjectsAllProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-projects/AllProject': typeof AllProjectsAllProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all-projects/AllProject'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all-projects/AllProject'
  id: '__root__' | '/' | '/all-projects/AllProject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllProjectsAllProjectRoute: typeof AllProjectsAllProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-projects/AllProject': {
      id: '/all-projects/AllProject'
      path: '/all-projects/AllProject'
      fullPath: '/all-projects/AllProject'
      preLoaderRoute: typeof AllProjectsAllProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllProjectsAllProjectRoute: AllProjectsAllProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
